# -*- coding: utf-8 -*-
"""180123048_lab11_q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10l4q7gb4J85lp6yPMWQfGqbDDVnw6Mui
"""

import numpy as np
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10,8)

beta = [0.02,0.7,0.06]
mu = [0.7,0.1,0.09]
sigma = [0.02,0.3,0.5]
r_0 = [0.1,0.2,0.02]

def cir(beta,mu,t,T,sig,r):
  gamma = np.sqrt(beta**2+2*sig**2)
  x = T-t
  B = (2*np.exp(gamma*x)-1)/((gamma+beta)*(np.exp(gamma*x)-1)+2*gamma)
  A = ((2*gamma*np.exp((beta+gamma)*(x/2)))/(((gamma+beta)*(np.exp(gamma*x)-1)+2*gamma)))**(2*beta*mu/(sig**2))
  result = A*np.exp(-1*B*r)
  return result

T = 1
t = np.linspace(0,T,10)

for i in range(0,3):
  values = np.zeros((1,10)).ravel()
  for j in range(0,10):
    temp = cir(beta[i],mu[i],t[j],T,sigma[i],r_0[i])
    values[j] = np.log(temp)/(t[j]-T)
  plt.plot(t,values,'-*')
  plt.xlabel('t',size=15)
  plt.ylabel('r',size=15)
  str = "Yield vs time(t) -- Set:{}".format(i+1)
  plt.title(str,size=20)
  plt.grid()
  plt.show()

T = np.linspace(0.1,1,600)
r = np.linspace(0.1,1,10)
t = 0
for i in range(0,1):
  for k in range(0,10):
    values = np.zeros((1,600)).ravel()
    for j in range(0,600):
      temp = cir(beta[i],mu[i],t,T[j],sigma[i],r[k])
      values[j] = np.log(temp)/(t-T[j])
    plt.plot(T,values)
  plt.xlabel('T',size=15)
  plt.ylabel('r',size=15)
  str = "Yield vs Maturity(T)"
  plt.title(str,size=20)
  plt.grid()
  plt.show()