# -*- coding: utf-8 -*-
"""180123048_lab11_q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15JeA3C8RgMH2XEuUiQmrGlG5E6nhgFu3
"""

import numpy as np
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10,8)

beta = [5.9,3.9,0.1]
mu = [0.2,0.1,0.4]
sigma = [0.3,0.3,0.11]
r_0 = [0.1,0.2,0.1]
T = 1
t = np.linspace(0,T,10)

def vasicek(beta,mu,t,T,sig,r):
  a = beta
  b = beta*mu
  B = (1-np.exp(-a*(T-t)))/a
  A = (B-T-t)*(a*b-0.5*sig*sig)/(a**2) - (sig**2*B**2)/(4*a)
  result = np.exp(A-B*r)
  return result

for i in range(0,3):
  values = np.zeros((1,10)).ravel()
  for j in range(0,10):
    temp = vasicek(beta[i],mu[i],t[j],T,sigma[i],r_0[i])
    values[j] = np.log(temp)/(t[j]-T)
  plt.plot(t,values,'-*')
  plt.xlabel('t',size=15)
  plt.ylabel('r',size=15)
  str = "Yield vs time(t) -- Set:{}".format(i+1)
  plt.title(str,size=20)
  plt.grid()
  plt.show()

T = np.linspace(0,1,500)
r = np.linspace(0.1,0.99,10)
t = 0
for i in range(0,3):
  for k in range(0,10):
    values = np.zeros((1,500)).ravel()
    for j in range(0,500):
      temp = vasicek(beta[i],mu[i],t,T[j],sigma[i],r[k])
      values[j] = np.log(temp)/(t-T[j])
    plt.plot(T,values)
  plt.xlabel('T',size=15)
  plt.ylabel('r',size=15)
  str = "Yield vs Maturity(T) -- Set:{}".format(i+1)
  plt.title(str,size=20)
  plt.grid()
  plt.show()