# -*- coding: utf-8 -*-
"""Lab07_180123048_subhamkumar_q4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u6DVuUs3j95JI0wsjGJ_Nk06yWQ_vvtl
"""

import math
import numpy as np
from scipy.stats import norm
import matplotlib.pyplot as plt
from matplotlib import cm

def european_option_prices(T,K,S,r,sig,t):
  
  if T == t:
    putp = max(K-S,0)
    callp = max(S-K,0)
    return(callp,putp)
  d_1 = (math.log(S/K)+(r+sig**2/2)*(T-t))/(sig*math.sqrt(T-t))
  d_2 = d_1-sig*math.sqrt(T-t)
  putp = K*math.exp(-r*(T-t))*norm.cdf(-1*d_2) - S*norm.cdf(-1*d_1)
  callp = S*norm.cdf(d_1) - K*norm.cdf(d_2)*math.exp(-r*(T-t))
  return(callp,putp)

def Graph3(X, Y, Z1, XLabel, YLabel, G1):
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    ax.plot_surface(np.array(X), np.array(Y), np.array(Z1),cmap=cm.viridis)
    ax.set_xlabel(XLabel, size=10)
    ax.set_ylabel(YLabel, size=10)
    
    plt.title(G1, size= 15)
    plt.figure(figsize=(16,9))
    plt.show()

T=1
K=1
r=0.05
sig=0.6

t = [0, 0.2, 0.4, 0.6, 0.8,1]
var = np.linspace(0.5,3,26)

call_p = np.zeros([len(t),len(var)])
put_p = np.zeros([len(t),len(var)])

for i in range(0,len(t)):
  for j in range(0,len(var)):
    call_p[i][j],put_p[i][j] = european_option_prices(1,var[j],1,0.05,0.6,t[i])

for i in range(0,len(t)):
  plt.plot(var,call_p[i][:],label = str(t[i]),linewidth=2)
plt.grid()
plt.xlabel('Strike price')  
plt.ylabel('Option price')
plt.title('Sensitivity of Call prices with varying K', size= 15)
plt.legend()
plt.figure(figsize=(16,9))
plt.show()

for i in range(0,len(t)):
  plt.plot(var,put_p[i][:],label = str(t[i]))
plt.grid()
plt.xlabel('Strike price')  
plt.ylabel('Option price')
plt.title('Sensitivity of Put prices with varying K', size= 15)
plt.legend(loc="upper left")
plt.figure(figsize=(20 ,15))
plt.show()

time = []

for j in range(0,6):
  for i in range(0,26):
    
    time.append(t[j])
  
X  = np.reshape(time, (6, 26))

Y = []
for j in range(0,6):
  Y.append(var)

Y = np.reshape(Y, (6, 26))
Y

Graph3(X, Y,call_p , "Time", "Strike price", "Call prices varying K")

Graph3(X, Y,put_p , "Time", "Strike price", "Put prices varying K")

var = np.linspace(0.01,0.9,90)
call_p = np.zeros([len(t),len(var)])
put_p = np.zeros([len(t),len(var)])
for i in range(0,len(t)):
  for j in range(0,len(var)):
    call_p[i][j],put_p[i][j] = european_option_prices(T,K,1,var[j],sig,t[i])

for i in range(0,len(t)):
  plt.plot(var,call_p[i][:],label = str(t[i]),linewidth=2)
plt.grid()
plt.xlabel('Interest rate')  
plt.ylabel('Option price')
plt.title('Sensitivity of Call prices with varying r', size= 15)
plt.legend()
plt.figure(figsize=(16,9))
plt.show()

for i in range(0,len(t)):
  plt.plot(var,put_p[i][:],label = str(t[i]),linewidth=2)
plt.grid()
plt.xlabel('Interest rate')  
plt.ylabel('Option price')
plt.title('Sensitivity of Put prices with varying r', size= 15)
plt.legend()
plt.figure(figsize=(16,9))
plt.show()

time = []

for j in range(0,6):
  for i in range(0,90):
    
    time.append(t[j])
  
X  = np.reshape(time, (6, 90))

Y = []
for j in range(0,6):
  Y.append(var)

Y = np.reshape(Y, (6, 90))

Graph3(X, Y,call_p , "Time", "Interest rate", "Call prices varying interest rate")

Graph3(X, Y,put_p , "Time", "Interest rate", "Put prices varying interest rate")

var = np.linspace(0.1,0.5,5)
call_p = np.zeros([len(t),len(var)])
put_p = np.zeros([len(t),len(var)])
for i in range(0,len(t)):
  for j in range(0,len(var)):
    call_p[i][j],put_p[i][j] = european_option_prices(T,K,1,r,var[j],t[i])

for i in range(0,len(t)):
  plt.plot(var,call_p[i][:],label = str(t[i]),linewidth=2)
plt.grid()
plt.xlabel('Volatility')  
plt.ylabel('Option price')
plt.title('Sensitivity of Call prices with varying sigma', size= 15)
plt.legend()
plt.figure(figsize=(16,9))
plt.show()

for i in range(0,len(t)):
  plt.plot(var,put_p[i][:],label = str(t[i]),linewidth=2)
plt.grid()
plt.xlabel('Volatility')  
plt.ylabel('Option price')
plt.title('Sensitivity of Put prices with varying sigma', size= 15)
plt.legend()
plt.figure(figsize=(16,9))
plt.show()

time = []

for j in range(0,6):
  for i in range(0,5):
    
    time.append(t[j])
  
X  = np.reshape(time, (6, 5))

Y = []
for j in range(0,6):
  Y.append(var)

Y = np.reshape(Y, (6, 5))

Graph3(X, Y,call_p , "Time", "Sigma", "Call prices varying sigma")

Graph3(X, Y,put_p , "Time", "Sigma", "Put prices varying sigma")

var = np.linspace(1.1,3,20)
call_p = np.zeros([len(t),len(var)])
put_p = np.zeros([len(t),len(var)])
for i in range(0,len(t)):
  for j in range(0,len(var)):
    call_p[i][j],put_p[i][j] = european_option_prices(var[j],K,1,r,sig,t[i])

for i in range(0,len(t)):
  plt.plot(var,call_p[i][:],label = str(t[i]),linewidth=2)
plt.grid()
plt.xlabel('Expiry time')  
plt.ylabel('Option price')
plt.title('Sensitivity of Call prices with varying expiry time', size= 15)
plt.legend()
plt.figure(figsize=(16,9))
plt.show()

for i in range(0,len(t)):
  plt.plot(var,put_p[i][:],label = str(t[i]),linewidth=2)
plt.grid()
plt.xlabel('Expiry time')  
plt.ylabel('Option price')
plt.title('Sensitivity of Put prices with varying expiry time', size= 15)
plt.legend()
plt.figure(figsize=(16,9))
plt.show()

time = []

for j in range(0,6):
  for i in range(0,20):
    
    time.append(t[j])
  
X  = np.reshape(time, (6, 20))

Y = []
for j in range(0,6):
  Y.append(var)

Y = np.reshape(Y, (6, 20))

Graph3(X, Y,call_p , "Time", "Expiration time", "Call prices varying Expiration time")

Graph3(X, Y,put_p , "Time", "Expiration time", "Put prices varying Expiration time")