# -*- coding: utf-8 -*-
"""180123048_lab09_subhamkumar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PBzK2jbV6eVv2pY4nDXLVfnX4lebSdGG
"""

from pandas import read_csv, to_datetime
import numpy as np
from scipy.stats import norm
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

fields=['Expiry', 'Strike Price', 'Put Price', 'Call Price']
orig_data = read_csv('OptionNIFTY.csv', usecols=fields, index_col=False)

optionData = read_csv("OptionNIFTY.csv")
stockData = read_csv("nsedata1.csv")
optionData['Date2'] = to_datetime(optionData['Date'])
stockData['Date2'] = to_datetime(stockData['Date'])
stockData = stockData[['Date2','Close']]
data = optionData.merge(stockData,on='Date2')

data.head()

numSample = 1000
mask = np.random.randint(0, len(data), numSample)
data = data.loc[mask]

data.head()

import matplotlib.dates as mdates
plot_data = orig_data[:numSample]
plt.rcParams["figure.figsize"] = (20,12)

def plotPrices(plot_data):
    dates = to_datetime(plot_data['Expiry'])
    x = to_datetime(dates)
    x = mdates.date2num(x)

    y = plot_data['Strike Price']
    z_call = plot_data['Call Price']
    z_put = plot_data['Put Price']

    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')

    ax.scatter(x, y, z_call, c='b', marker='.', label='Call Option')

    plt.xticks(x, data['Expiry'], rotation=90)
    ax.set_xlabel('Maturity Date',size=20)
    ax.set_ylabel('Strike Price',size=20)
    ax.set_zlabel('Option Prices',size=20)
    
    ax.set_title("Maturity Vs Strike Price Vs Option Prices:Call Option",size=20)
    
    plt.show()

    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')

    ax.scatter(x, y, z_put, c='r', marker='.', label='Put Option')

    plt.xticks(x, data['Expiry'], rotation=90)
    ax.set_xlabel('Maturity Date',size=20)
    ax.set_ylabel('Strike Price',size=20)
    ax.set_zlabel('Option Prices',size=20)
    ax.set_title("Maturity Vs Strike Price Vs Option Prices:Put Option",size=20)
    

    plt.show()

plotPrices(plot_data)

def plotPrices1(plot_data):
    dates = to_datetime(plot_data['Expiry'])
    x = to_datetime(dates)
    x = mdates.date2num(x)

    y = plot_data['Strike Price']
    z_call = plot_data['Call Price']
    z_put = plot_data['Put Price']

    
    plt.scatter(x,z_call)
    plt.title('Maturity Vs Option Price:Call option',size=20)
    plt.xticks(x, data['Expiry'])
    plt.xlabel('Maturity Date',size=10)
    plt.ylabel('Option Price',size=10)
    plt.show()

    plt.scatter(x,z_put)
    plt.title('Maturity Vs Option Price:Put option',size=20)
    plt.xticks(x, data['Expiry'])
    plt.xlabel('Maturity Date',size=10)
    plt.ylabel('Option Price',size=10)
    plt.show()

plotPrices1(plot_data)

def plotPrices2(plot_data):
    dates = to_datetime(plot_data['Expiry'])
    x = to_datetime(dates)
    x = mdates.date2num(x)

    y = plot_data['Strike Price']
    z_call = plot_data['Call Price']
    z_put = plot_data['Put Price']

    
    plt.scatter(y,z_call)
    plt.title('Strike Price Vs Option Price:Call option',size=20)
    plt.xlabel('Strike Price',size=10)
    plt.ylabel('Option Price',size=10)
    plt.show()


    plt.scatter(y,z_put)
    plt.title('Strike Price Vs Option Price:Put option',size=20)
    plt.xlabel('Strike Price',size=10)
    plt.ylabel('Option Price',size=10)
    plt.show()

plotPrices2(plot_data)

def getCall(S, K, r, t, sig):
    d1 = (np.log(S/K)+t*(r+(sig**2)/2))/(sig*(t**0.5))
    d2 = d1-sig*(t**0.5)
    Nd1 = norm.cdf(d1)
    Nd2 = norm.cdf(d2)
    C = S*Nd1 - K*np.exp(-r*t)*Nd2
    return C

def getPut(S, K, r, t, sig):
    d1 = (np.log(S/K)+t*(r+(sig**2)/2))/(sig*(t**0.5))
    d2 = d1-sig*(t**0.5)
    Nd1 = norm.cdf(-d1)
    Nd2 = norm.cdf(-d2)
    P = K*np.exp(-r*t)*Nd2 - S*Nd1
    return P

def f(Price, St, K, r, t, sig, option='Call'):
    if option is 'Call':
        return getCall(St, K, r, t, sig)-Price
    else:
        return getPut(St, K, r, t, sig)-Price

def Secant(Price, St, K, r, t, option='Call'):
    x0 = 0.1
    x1 = 0.2
    
    tol = 0.00001
    num = 100
    alpha = 0.1
    for i in range(num):
        x2 = x1 - f(Price, St, K, r, t, x1, option)*(x1-x0)/(f(Price, St, K, r, t, x1, option)-f(Price, St, K, r, t, x0, option)+alpha)
        x0 = x1
        x1 = x2
#         print(x1, f(Price, St, K, r, t, x1, option))
        if abs(f(Price, St, K, r, t, x1, option)) < tol:
            break
    return x1

from datetime import datetime

num = len(data)
sig_c = np.zeros(num)
sig_p = np.zeros(num)
for i in range(num):
    St = data.iloc[-i]['Close']
    r = 0.05
    init_date=data.iloc[-i]['Date']
    exp_date=data.iloc[-i]['Expiry']
    
    date_format = "%d-%b-%Y"
    d0 = datetime.strptime(init_date, date_format)
    d1 = datetime.strptime(exp_date, date_format)
    t = (d1-d0).days/252
    K = data.iloc[-i]['Strike Price']
    P = data.iloc[-i]['Put Price']
    C = data.iloc[-i]['Call Price']
    
    sig_c[i] = Secant(C, St, K, r, t, 'Call')
    if abs(sig_c[i]) > 10:
        sig_c[i] = np.nan
#     if i%50 is 0:
#         print(str(i+1)+"/"+str(num))
    sig_p[i] = Secant(P, St, K, r, t, 'Put')
    if abs(sig_p[i]) > 10:
        sig_p[i] = np.nan

data['Volatility']=sig_c
data.drop(['Date2'], axis=1)
data.to_csv('result.csv', index=False)

data['Volatility_p']=sig_p

data.to_csv('result.csv', index=False)

def plotVolatility(data):
    dates = to_datetime(data['Expiry'])
    x = to_datetime(dates)
    x = mdates.date2num(x)

    y = data['Strike Price']
    z = data['Volatility']

    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')

    ax.scatter(x, y, z, c='b', marker='.', label='Call Option')

    plt.xticks(x, data['Expiry'], rotation=90)
    ax.set_xlabel('Maturity Date',size=15)
    ax.set_ylabel('Strike Price',size=15)
    ax.set_zlabel('Volatility',size=15)
    
    plt.title('Maturity vs Strike Price vs Volatility:Call option',size=20)
    plt.show()

def plotVolatility1(data):
    dates = to_datetime(data['Expiry'])
    x = to_datetime(dates)
    x = mdates.date2num(x)

    y = data['Strike Price']
    z = data['Volatility_p']

    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')

    ax.scatter(x, y, z, c='b', marker='.', label='Put Option')

    plt.xticks(x, data['Expiry'], rotation=90)
    ax.set_xlabel('Maturity Date',size=15)
    ax.set_ylabel('Strike Price',size=15)
    ax.set_zlabel('Volatility',size=15)
    
    plt.title('Maturity vs Strike Price vs Volatility:Put option',size=20)
    plt.show()

plotVolatility1(data)

def plotPrices5(data):
    dates = to_datetime(data['Expiry'])
    x = to_datetime(dates)
    x = mdates.date2num(x)

    y = data['Strike Price']
    z = data['Volatility_p']

    
    plt.scatter(x,z)
    plt.title('Maturity Vs Volatility:Put option',size=20)
    plt.xticks(x, data['Expiry'])
    plt.xlabel('Maturity Date',size=10)
    plt.ylabel('Volatility',size=10)
    plt.show()

def plotPrices6(data):
    dates = to_datetime(data['Expiry'])
    x = to_datetime(dates)
    x = mdates.date2num(x)

    y = data['Strike Price']
    z = data['Volatility_p']

    
    plt.scatter(y,z)
    plt.title('Strike Price Vs Volatility:Put option',size=20)
    plt.xlabel('Strike Price',size=10)
    plt.ylabel('Volatility',size=10)
    plt.show()

plotPrices5(data)
plotPrices6(data)

plotVolatility(data)

def plotPrices3(data):
    dates = to_datetime(data['Expiry'])
    x = to_datetime(dates)
    x = mdates.date2num(x)

    y = data['Strike Price']
    z = data['Volatility']

    
    plt.scatter(x,z)
    plt.title('Maturity Vs Volatility:Call option',size=20)
    plt.xticks(x, data['Expiry'])
    plt.xlabel('Maturity Date',size=10)
    plt.ylabel('Volatility',size=10)
    plt.show()

def plotPrices4(data):
    dates = to_datetime(data['Expiry'])
    x = to_datetime(dates)
    x = mdates.date2num(x)

    y = data['Strike Price']
    z = data['Volatility']

    
    plt.scatter(y,z)
    plt.title('Strike Price Vs Volatility:Call option',size=20)
    plt.xlabel('Strike Price',size=10)
    plt.ylabel('Volatility',size=10)
    plt.show()

plotPrices4(data)

plotPrices3(data)

